# Generated by Django 5.1.7 on 2025-04-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('constituent', models.TextField()),
                ('img', models.FileField(upload_to='food/')),
            ],
        ),
    ]
