# Generated by Django 5.1.7 on 2025-04-26 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_typesfood_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('constituent', models.TextField()),
                ('img', models.FileField(upload_to='food/')),
                ('typeFood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typesfood')),
            ],
        ),
    ]
